### ISSUE TITLE
Error Integration not found

### ISSUE THREAD

**Issue by toemsel1** [rsnodgrass/hass-sensorpush#10]
I installed the Sensorpush Addon via HACS and configured the configuration.yml but i have an Error:

```
Logger: homeassistant.setup
Source: setup.py:138
First occurred: 15:03:20 (11 occurrences)
Last logged: 15:03:20

Setup failed for severity: Integration not found.
Setup failed for entities: Integration not found.
Setup failed for type: Integration not found.
Setup failed for title: Integration not found.
Setup failed for entity: Integration not found.
```
Configuration.yml:
https://codeshare.io/5ekldA

Dont know what to do.

**Comment by rsnodgrass** [comment]
No sure what the configuration is that you posted, but the ONLY configuration for this in your configuration.yaml file should be:

```yaml
sensorpush:
  username: your@email.com
  password: YOURPASSWORD

sensor:
  - platform: sensorpush
```

There is no other configuration for sensorpush that should be in any YAML files (except in Lovelace).
