### ISSUE TITLE
Battery Value

### ISSUE THREAD

**Issue by Humphaz** [rsnodgrass/hass-sensorpush#6]
Hi,

I can see in the code the device battery status is detected, but I can't see it exposed anywhere.

Is it possible to read out the battery levels?

Best Regards,

Glyn

**Comment by cturra** [comment]
you can create a template sensor for `battery_voltage` by grabbing the state attribute from your sensorpush thermometer. here is an example of how you can do this (from my `configuration.yaml` file).

```
  - platform: template
    sensors:
      fridge_sensor_battery_voltage:
        friendly_name: 'Fridge SensorPush battery voltage'
        unit_of_measurement: 'V'
        value_template: '{{ state_attr("sensor.fridge_humidity", "battery_voltage") }}'
```
in my case, i am checking the voltage of the thermometer in my fridge and if the value gets too low, get notified it's time to change the battery (still need to watch a battery cycle to determine what the correct low voltage to alert on is). from the above, the new sensor you can use is: `fridge_sensor_battery_voltage`.
